"""Exploratory hypotheses building on the v1+Tier 3 findings.

A1 / C1 — "low-number bias":
    Players often pick numbers tied to dates (1–31) and other low numbers.
    If true, sorteos whose drawn combo contains MORE low numbers should
    be MORE likely to have at least one winner (because more tickets
    play that combo), so jackpot_won rate increases with lowness.
    A1: explains why Retro (6/39 — 79% of range is ≤31) shows the
    strongest behavior signal.
    C1: the directly actionable implication — to maximise EV conditional
    on winning, avoid the popular (low) numbers.

B1 — "BOLSA dependence":
    When the BOLSA grows, more tickets are sold and a different mix of
    players (more Quick Pick, fewer regulars) buys them. The empirical
    jackpot rate per sorteo should rise with BOLSA; the QUESTION is
    whether the rise is steeper than a uniform Poisson model would
    predict for the same ticket-count growth, which would indicate that
    conscious selection is diluted at high BOLSA.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
from matplotlib.figure import Figure
from scipy import stats


@dataclass
class LowNumberBiasResult:
    n_draws: int
    low_cutoff: int
    per_bucket: pd.DataFrame   # lowness_bucket, n_draws, n_jackpots, jackpot_rate
    chi2_stat: float
    chi2_dof: int
    p_value: float
    fig: Figure


@dataclass
class BolsaDependenceResult:
    n_draws: int
    per_tercile: pd.DataFrame  # tercile, bolsa_lo, bolsa_hi, n_draws, n_jackpots, jackpot_rate
    chi2_stat: float
    chi2_dof: int
    p_value: float
    fig: Figure


def _lowness_per_draw(draws_wide: pd.DataFrame, n_balls: int,
                       low_cutoff: int) -> np.ndarray:
    ball_cols = [f"r{i}" for i in range(1, n_balls + 1)]
    return (draws_wide[ball_cols] <= low_cutoff).sum(axis=1).to_numpy(dtype=int)


def low_number_bias_test(
    draws_wide: pd.DataFrame,
    jackpot_df: pd.DataFrame,
    *,
    range_: int,
    n_balls: int,
    low_cutoff: int = 31,
) -> LowNumberBiasResult:
    """Test whether jackpot_won rate correlates with lowness of the drawn combo.

    Joins draws_wide and jackpot_df on `draw`. Restricts to resolved sorteos
    (jackpot_won NA dropped, ambiguous excluded). Groups by lowness bucket
    (one bucket per possible lowness value in [0, n_balls]) and tests
    independence of lowness × jackpot_won via chi².
    """
    # Positional alignment: jackpot_df is constructed from draws_wide["award"]
    # in the same order, so row k of jackpot_df corresponds to row k of
    # draws_wide. Joining by jackpot_df["draw"] (which is a synthetic 1..n
    # generated by derive_jackpot_won) against draws_wide["draw"] (the real
    # CONCURSO numbers) drops most rows for products with DEFAULT_SINCE > 1.
    ordered_wide = draws_wide.sort_values("draw").reset_index(drop=True)
    ordered_jp = jackpot_df.reset_index(drop=True)
    if len(ordered_wide) != len(ordered_jp):
        raise ValueError(
            f"draws_wide ({len(ordered_wide)}) and jackpot_df ({len(ordered_jp)}) "
            "must have the same length (same source)"
        )
    merged = ordered_jp.copy()
    merged["lowness"] = _lowness_per_draw(ordered_wide, n_balls, low_cutoff)
    merged = merged.dropna(subset=["jackpot_won"])
    merged = merged[~merged["ambiguous"]]
    merged["jp_bool"] = merged["jackpot_won"].astype(bool)

    rows = []
    for lowness in range(0, n_balls + 1):
        sub = merged[merged["lowness"] == lowness]
        n = len(sub)
        if n == 0:
            continue
        n_jp = int(sub["jp_bool"].sum())
        rows.append({
            "lowness_bucket": int(lowness),
            "n_draws": n,
            "n_jackpots": n_jp,
            "jackpot_rate": n_jp / n if n else float("nan"),
        })
    per_bucket = pd.DataFrame(rows).sort_values("lowness_bucket").reset_index(drop=True)

    # Chi² of independence on the (lowness × jackpot_won) contingency table.
    contingency = np.array([
        [r["n_jackpots"], r["n_draws"] - r["n_jackpots"]]
        for r in per_bucket.to_dict(orient="records")
    ])
    if contingency.shape[0] < 2 or contingency.sum() == 0:
        chi2_stat, p_value, dof = float("nan"), float("nan"), 0
    else:
        chi2_stat, p_value, dof, _ = stats.chi2_contingency(contingency)
        chi2_stat = float(chi2_stat)
        p_value = float(p_value)

    expected_lowness_mean = n_balls * low_cutoff / range_

    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(10, 4))
    if not per_bucket.empty:
        # Bubble plot: x = lowness, y = jackpot_rate, size ∝ n_draws.
        ax.scatter(
            per_bucket["lowness_bucket"], per_bucket["jackpot_rate"],
            s=20 + 4 * per_bucket["n_draws"], color="steelblue", alpha=0.5,
            edgecolors="navy",
        )
        # Reference: uniform mean rate
        overall_rate = merged["jp_bool"].mean()
        ax.axhline(overall_rate, color="red", linestyle="--",
                   label=f"overall rate = {overall_rate:.3f}")
        ax.axvline(expected_lowness_mean, color="gray", linestyle=":",
                   alpha=0.6, label=f"expected mean lowness = {expected_lowness_mean:.2f}")
        ax.set_xlabel(f"lowness (count of balls ≤ {low_cutoff})")
        ax.set_ylabel("jackpot_won rate")
        ax.set_title(
            f"Jackpot rate by lowness (cutoff={low_cutoff}); "
            f"χ²={chi2_stat:.2f}, dof={dof}, p={p_value:.4f}"
        )
        ax.legend()
    fig.tight_layout()

    return LowNumberBiasResult(
        n_draws=int(len(merged)),
        low_cutoff=int(low_cutoff),
        per_bucket=per_bucket,
        chi2_stat=chi2_stat,
        chi2_dof=int(dof),
        p_value=p_value,
        fig=fig,
    )


def bolsa_dependence_test(
    draws_wide: pd.DataFrame,
    jackpot_df: pd.DataFrame,
    *,
    range_: int,
    n_balls: int,
) -> BolsaDependenceResult:
    """Test whether jackpot_won rate correlates with BOLSA tercile.

    Joins on `draw`, filters to resolved + non-ambiguous + award > 0.
    Splits sorteos into three terciles by award. Chi² of independence
    on the (tercile × jackpot_won) contingency table.
    """
    # No join with draws_wide needed — BOLSA comes from jackpot_df["award"]
    # directly, which is the same column the F0.5 derivation used.
    merged = jackpot_df.copy().reset_index(drop=True)
    merged = merged.dropna(subset=["jackpot_won"])
    merged = merged[~merged["ambiguous"]]
    merged = merged[merged["award"] > 0]
    merged["jp_bool"] = merged["jackpot_won"].astype(bool)

    # Tercile thresholds (ranks 1, 2, 3).
    try:
        merged["tercile"] = pd.qcut(merged["award"], q=3, labels=[1, 2, 3])
    except ValueError:
        # All awards identical → cannot stratify.
        merged["tercile"] = 2

    rows = []
    for t in sorted(merged["tercile"].unique()):
        sub = merged[merged["tercile"] == t]
        n = len(sub)
        n_jp = int(sub["jp_bool"].sum())
        rows.append({
            "tercile": int(t),
            "bolsa_lo": float(sub["award"].min()),
            "bolsa_hi": float(sub["award"].max()),
            "n_draws": n,
            "n_jackpots": n_jp,
            "jackpot_rate": n_jp / n if n else float("nan"),
        })
    per_tercile = pd.DataFrame(rows).sort_values("tercile").reset_index(drop=True)

    contingency = np.array([
        [r["n_jackpots"], r["n_draws"] - r["n_jackpots"]]
        for r in per_tercile.to_dict(orient="records")
    ])
    if contingency.shape[0] < 2 or contingency.sum() == 0:
        chi2_stat, p_value, dof = float("nan"), float("nan"), 0
    else:
        chi2_stat, p_value, dof, _ = stats.chi2_contingency(contingency)
        chi2_stat = float(chi2_stat)
        p_value = float(p_value)

    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(10, 4))
    if not per_tercile.empty:
        xs = per_tercile["tercile"].astype(int)
        ax.bar(xs, per_tercile["jackpot_rate"], color="steelblue", alpha=0.6,
               edgecolor="navy", label="observed jackpot rate")
        overall_rate = merged["jp_bool"].mean()
        ax.axhline(overall_rate, color="red", linestyle="--",
                   label=f"overall rate = {overall_rate:.3f}")
        ax.set_xticks(xs)
        ax.set_xticklabels([
            f"T{t}\n[{lo/1e6:.0f}M–{hi/1e6:.0f}M]"
            for t, lo, hi in zip(
                per_tercile["tercile"], per_tercile["bolsa_lo"],
                per_tercile["bolsa_hi"]
            )
        ])
        ax.set_ylabel("jackpot_won rate")
        ax.set_title(
            f"Jackpot rate by BOLSA tercile  "
            f"χ²={chi2_stat:.2f}, dof={dof}, p={p_value:.4f}"
        )
        ax.legend()
    fig.tight_layout()

    return BolsaDependenceResult(
        n_draws=int(len(merged)),
        per_tercile=per_tercile,
        chi2_stat=chi2_stat,
        chi2_dof=int(dof),
        p_value=p_value,
        fig=fig,
    )
